### ISSUE TITLE
Scrolling inertia does not work

### ISSUE THREAD

**Issue by trevorshannon** [5calls/android#1]
Most mobile apps support scrolling with "inertia" so that the page keeps scrolling if you flick it up or down.  This doesn't work on the 5calls app.

**Comment by dektar** [comment]
On it! Thanks.

**Comment by levibostian** [comment]
@dektar I got this done. I am making a PR now.

**Comment by dektar** [comment]
Oh, I just did it!

**Comment by dektar** [comment]
Fixed in https://github.com/5calls/android/commit/04b2941c792bd9c61dd9b717223c6d85e3685ea8. @levibostian let me know if you want to work on something else!
