### ISSUE TITLE
Android app selects wrong state representatives

### ISSUE THREAD

**Issue by jdrch** [5calls/android#116]
Has anyone else noticed this? I live in IA, and entering my home zip code gives me the wrong representatives. So does using my GPS location.

Any ideas?

**Comment by nickoneill** [comment]
Hi @jdrch, are you talkinig about state level legislators (IA general assembly) or your congressional reps from your state?

**Comment by jdrch** [comment]
State level legislators, so IA general assembly. The ones the app
shows for me are actually from neighboring districts, not my own. One
option might be to add full street address lookup functionality, but a
quicker stopgap might be to allow us to choose our state assembly reps
manually if we know them.

**Comment by nickoneill** [comment]
You can absolutely use a street address in the manual location box, see if you get better results in that case. We use the data from openstates.org which is pretty consistently updated. Let me know if you still have trouble.

**Comment by jdrch** [comment]
Ah, I didn't realize you could do that! Thought it was zip codes only. Entering full street address with zip and state fixes the problem. Thanks!
