### ISSUE TITLE
Not all outcome buttons display

### ISSUE THREAD

**Issue by chadschultz** [5calls/android#117]
I recently started using 5 Calls, and ran into an issue on my Pixel 2 XL (Android 10). For some issues, only the "UNAVAILABLE" button would display. "LEFT VOICEMAIL" and "MAKE CONTACT" would not.

Here I am at the bottom of the screen, only able to show one button:

![device-2020-06-05-190336](https://user-images.githubusercontent.com/1164989/83931036-2359ad00-a760-11ea-85e8-31ae4db22888.png)

But if I turn the screen sideways, I see all the buttons:

![device-2020-06-05-190240](https://user-images.githubusercontent.com/1164989/83931039-2bb1e800-a760-11ea-8839-2a2fa6f1be17.png)

Here's a different issue that doesn't have the problem - all three buttons show in portrait mode.

![device-2020-06-05-190353](https://user-images.githubusercontent.com/1164989/83931064-4d12d400-a760-11ea-8045-c1b858a2c31e.png)

My guess is that it's based on exactly how tall the screen space is and how tall the content is, so it may be tricky to reproduce unless you use the same device and view the same issue (or find a different combination that reproduces the problem)

**Comment by nickoneill** [comment]
@chadschultz I added this to a new 2.2.0 release - let me know if you see anything small we should include, otherwise I will make a new build for the store.

**Comment by chadschultz** [comment]
@nickoneill I'm not aware of anything else pressing - I'd say to go ahead and publish.

**Comment by nickoneill** [comment]
Great, will do. Not a priority for this release but if you want to look into something, #119 came up when I was testing this morning. I assume staying updated with the latest gradle is a good thing on android?

**Comment by chadschultz** [comment]
Definitely a good idea, much like keeping libraries updated in general.
It's not critical though, it won't cause things to fall apart in the near
future. When I was setting up the code I noticed a lot that should be done
to keep it up to date... moving from the old Android support libraries to
AndroidX (which would require changing from Google Analytics to Firebase
Analytics on the client side), updating to Gradle yes, and it would be a
good idea to use the latest version of all libraries when we can.
Beyond that, it's nice to dream of making the project structure a bit
cleaner, kotlinifying the codebase, refactoring to a decent architecture
pattern (such as MVVM) and adding unit testing/UI testing would be lovely.
The good news is, if some of that work was done, I feel like it would be
easier for people to contribute to the project. On the other hand, it is a
pretty simple app and has gone this long without major bugs.
Anyway, although I'm excited by the possibilities, I'm reluctant to commit
too much - it would be easy for me to get distracted from other projects,
such as my efforts to get a job. This week in particular I'm focusing
exclusively on working through one company's application process. In the
coming weeks I may or may not make some updates to the 5 Calls app... we'll
have to see how well I manage my time.
