### ISSUE TITLE
Add Re-engagement notifications

### ISSUE THREAD

**Issue by Gregliest** [5calls/android#19]
Along with a turn off and snooze option.

**Comment by dektar** [comment]
With https://developer.android.com/reference/android/app/AlarmManager.html this shouldn't be too much hassle. Needs some UX thought.

**Comment by dektar** [comment]
Plan:
Local weekday reminders. User can set a time of day, and turn off or on the reminders, in settings. Users cannot control which days -- we just do all weekdays.

New users will see info about this in the tutorial screen. Old users will get a note when they upgrade the app that the feature is added. But we will have it on by default.

Reminder will potentially have a snooze option (lower priority). Clicking the reminder brings you to 5calls and logs to analytics that you came from the reminder.

**Comment by dektar** [comment]
Still TODO: Snooze option, UX review.
