### ISSUE TITLE
Zip code text field state is lost when app is backgrounded

### ISSUE THREAD

**Issue by trevorshannon** [5calls/android#2]
On Android N.

Steps to reproduce:

1. Open the app and enter a zip code.
2. Hit the 'Edit' button next to the entered zip code. (Currently selected zip code is pre-populated in the text field)
3. Hit the android system back button
4. Hit the android running apps button and select 5calls
5. Hit the 'Edit' button next to the entered zip code.  Text field is not pre-populated any more.

**Comment by dektar** [comment]
This is no longer relevant in the new location activity.
