### ISSUE TITLE
current zip code is updated but issue list is stale when offline

### ISSUE THREAD

**Issue by trevorshannon** [5calls/android#4]
If the device is offline, e.g. in airplane mode, and a user attempts to change the zip code, a notification fires that the device is not online and the list of issues is not updated (as there is no connection).

However, the header that shows which zip code is currently selected *does* update and thus does not match the displayed list of issues.

**Comment by dektar** [comment]
Also fixed in https://github.com/5calls/android/commit/04b2941c792bd9c61dd9b717223c6d85e3685ea8.
