### ISSUE TITLE
NPE when API sends null JSON array

### ISSUE THREAD

**Issue by dektar** [5calls/android#52]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONArray.toString()' on a null object reference
	at org.a5calls.android.a5calls.model.FiveCallsApi$1.onResponse(FiveCallsApi.java:94)
	at org.a5calls.android.a5calls.model.FiveCallsApi$1.onResponse(FiveCallsApi.java:82)

**Comment by nickoneill** [comment]
Interesting! I wonder when this occurs from the server side?

**Comment by dektar** [comment]
It happened around 7:30 am PST yesterday. I think we got a JSON response but the "issues" array was totally missing, and I had an assumption that if we got any JSON then the "issues" array would be present.
