### ISSUE TITLE
DB crashes trying to insert TX-BetoO'Rourke

### ISSUE THREAD

**Issue by dektar** [5calls/android#53]
We should escape that character on the DB side.

**Comment by nickoneill** [comment]
Missed this one on my side too, we already strip a few other characters from these names. We can fix in both locations.

**Comment by dektar** [comment]
@nickoneill If you change this in the API side, will you be stripping the character or escaping it? I'd want to match what you do so that I don't end up storing two different contact IDs in my local DB.

**Comment by dektar** [comment]
Submitted sanitizing anyway because some users might already have those strings in their databases.
