### ISSUE TITLE
Link to get in contact with 5 calls from the about page

### ISSUE THREAD

**Issue by dektar** [5calls/android#60]
Links to 5 calls' twitter, facebook and instagram also would be cool.

**Comment by dektar** [comment]
The email link should be an intent that sets the subject and mailto fields.

**Comment by dektar** [comment]
@nickoneill What email subject would you like for feedback coming directly from the Android app (in a future release)?

**Comment by nickoneill** [comment]
"Feedback from 5 Calls Android App" is good!

**Comment by hblumberg** [comment]
I'm going to give this a try!

**Comment by hblumberg** [comment]
@dektar I'm also happy to add the social media links. Do you have a design in mind?

**Comment by nickoneill** [comment]
Fixed in #90 - Thanks @hblumberg!

**Comment by nickoneill** [comment]
Sorry, outdated github page 😭 feel free to continue discussion social media

**Comment by hblumberg** [comment]
I'm going to work on adding social media links! (Discussing design in Slack.)

**Comment by nickoneill** [comment]
Fixed in #121
