### ISSUE TITLE
Use tabbed header to get to issues list, about, your impact, and a "why calling works" screen

### ISSUE THREAD

**Issue by dektar** [5calls/android#62]
Will make impact and others more discoverable

**Comment by dektar** [comment]
Or maybe the Navigation Drawer would work well? https://developer.android.com/training/implementing-navigation/nav-drawer.html

**Comment by nickoneill** [comment]
Nav drawer is an interesting idea - the examples given there have sort of a profile-y feel to the top of them, then a list of items underneath. Feels like the impact details could be always on that drawer, up top and the links to other sections could be below.
