### ISSUE TITLE
Sort issues I have no calls for to the bottom

### ISSUE THREAD

**Issue by SomeKittens** [5calls/android#79]
Sometimes, issues pop up that have no calls for me to make.  Can these be sorted to the bottom and/or greyed out to indicate that there's no action necessary?

**Comment by dektar** [comment]
Thanks! I agree that this should be better, and I think a bigger issue here is that you probably live in a split district and didn't enter a specific enough address to get your reps in the house, and the app needs to do a better job alerting you to that.

To get reps for all the issues, try entering a more full address into the location page -- including a street, for example. (Let me know if that isn't why you end up with no reps for some issues.)

**Comment by dektar** [comment]
In fact, we should never return issues that have no calls to make -- so we should solve this by telling the user about split district.
