### ISSUE TITLE
Integrate with OneSignal for notifications

### ISSUE THREAD

**Issue by dektar** [5calls/android#97]

**Comment by nickoneill** [comment]
For the distinction between people who want all or just important notifications, I was thinking of using tags in onesignal. A user who just want important notifications can have no tags, and one that wants all can have the 'all' tag.

(this from my very brief reading on how one signal tags work, let me know if I'm not reading it correctly)

**Comment by dektar** [comment]
Tags sounds good. For my reference: https://documentation.onesignal.com/v3.0/docs/android-native-sdk#section-tags

To enable opt-in and opt-out fully in settings, we can use setSubscription: https://documentation.onesignal.com/v3.0/docs/android-native-sdk#section--setsubscription-.

**Comment by dektar** [comment]
When to prompt for notification types? When they've first made all the calls on an issue. Disable notifications until the prompt is first shown. If the user enables it in settings first, never show the prompt.
